name: DevChat Electron CI
on:
  push:
    branches:
      - release

  workflow_dispatch:

env:
  REPO_ID: devchat-web-electron
  GITHUB_TOKEN: ${{ secrets.SECRET_GITHUB_TOKEN }}

jobs:
  build-on-win:
    runs-on: windows-latest
    steps:
      - name: Checkout to repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ env.SECRET_GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: Install dependencies on submodule
        run: |
          cd devchat-web
          yarn
      - name: Build submodule
        run: |
          cd devchat-web
          NODE_ENV=electron yarn build:electron
      - name: Install dependencies
        run: yarn
      - name: Build & publish Electron app
        run: yarn run publish
