name: Create pull request when main branch is updated
on:
  push:
    branches:
      - main

env:
  REPO_ID: devchat-web-electron

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.SECRET_GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/sep-devchat/${{ env.REPO_ID }}/pulls \
          -d '{"title":"Release ","body":"Release request trigged by github ci","head":"main","base":"release"}'
